export const gameOptions ={
    //游戏重力
    gravity:1,
    //石头的个数
    storenum:4,
    //星星的个数
    starsnum:3,
    //石头的标签label
    STORE:2,
    //星星的标签label
    STAR:1,
    //玩家的标签label
    PLAYER:0,
    //石头半径
    storeRadius:25,
    //约束收缩速度
    constraintSpeed:4,
    //每次游戏的事件，计时器中的时间
    initialTime:60,
    //存储当前的分数
    localStorageName:'bestScore',
    //非碰撞组索引
    nonicollosion:1,
    //碰撞组索引
    icollosion:2,
    //当前关卡
    localStorageName1:'level',
    //第一关的目标分数
    target_1:10

}